apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minetest-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mhefner/minetest-kube.git  # <-- your git repo here
    targetRevision: HEAD
    path: minetest
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
