apiVersion: apps/v1
kind: Deployment
metadata:
  name: minetest
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minetest
  template:
    metadata:
      labels:
        app: minetest
    spec:
      tolerations:
      - key: "arch"
        operator: "Equal"
        value: "amd64"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/arch"
                operator: "In"
                values:
                - ig11-74bb3a41
      containers:
      - name: minetest
        image: mhefner1983/minetest_kube:x86
        args: ["/usr/games/minetestserver", "--world", "/data/world"]
        ports:
        - containerPort: 30000
          protocol: UDP
        volumeMounts:
        - name: world-storage
          mountPath: /data/world
      volumes:
      - name: world-storage
        persistentVolumeClaim:
          claimName: minetest-pvc
