apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minetest-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: minetest-pv
  storageClassName: ""   # make sure this matches PV
