apiVersion: v1
kind: PersistentVolume
metadata:
  name: minetest-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.60    # <-- Your NFS server IP here
    path: /mnt/storage/minetest    # <-- Your exported NFS path
  persistentVolumeReclaimPolicy: Retain
