apiVersion: v1
kind: Service
metadata:
  name: minetest-service
  namespace: default
spec:
  selector:
    app: minetest
  ports:
    - protocol: UDP
      port: 30000
      targetPort: 30000
  type: ClusterIP
