apiVersion: v1
kind: PersistentVolume
metadata:
  name: minetest-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""       # disable dynamic provisioning
  nfs:
    server: 10.0.0.60
    path: /mnt/storage/minetest
